kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- configmap.yaml
- secret.yaml
- ingress.yaml
- service.yaml
- statefulset.yaml

commonLabels:
  role: pingaccess

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingaccess-environment-variables
  envs:
  - env_vars