apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingaccess-passwords
data:
  INITIAL_ADMIN_PASSWORD: MkZlZGVyYXRlTTByZQ==

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingaccess-license