kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- configmap.yaml
- hpa.yaml
- secret.yaml
- ingress.yaml
- service.yaml
- statefulset.yaml

commonLabels:
  role: pingaccess

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingaccess-environment-variables
  envs:
  - env_vars

vars:
- name: K8S_STATEFUL_SET_SERVICE_NAME_PINGACCESS_ADMIN
  objref:
    kind: Service
    name: pingaccess-admin
    apiVersion: v1
- name: K8S_STATEFUL_SET_NAME_PINGACCESS
  objref:
    kind: StatefulSet
    name: pingaccess
    apiVersion: apps/v1