kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- secret.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  role: pingfederate

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingfederate-environment-variables
  envs:
  - env_vars
