apiVersion: v1
kind: Secret
metadata:
  name: pingfederate-license
type: Opaque

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingfederate-jwk
data:
  pf.jwk:
    eyJrZXlzIjpbeyJrdHkiOiJvY3QiLCJraWQiOiJFbUljVTE5V255IiwiayI6ImdVMlpqN1JSd0hTRjhUQWtHUS1JMVRncmNHOHFWWGp0aGtLUHVmY0ZYemsifSx7Imt0eSI6Im9jdCIsImtpZCI6IjJuTmxLdGM5RHAiLCJrIjoiNWY2aDVmaGR2N0oxeWE1WXMtbkpoTmpPWVZEV19VZzBlSEpXb3Q1M0UybyJ9LHsia3R5Ijoib2N0Iiwia2lkIjoib3A2ZVBkVmM3UCIsImsiOiJfTlZkWGtMLVpaOUJDb0RhajdURElVUk4wNi0wek52UThzcG82QU5xNFNnIn0seyJrdHkiOiJvY3QiLCJraWQiOiJObWJWM0V2WWl0IiwiayI6InAxNXlvM290ak5xNkdkVHZnVHFIWVgwUkZjSkNOWFZxNFlDUEtKWm1pQzgifSx7Imt0eSI6Im9jdCIsImtpZCI6IkdDUWNjZjRaOVMiLCJrIjoiSGZOeUxNLUZGUTZCbkZTdHl3Q0JVd2dRYmtHb2pFMVRCVWJWWVNzR2hFZyJ9LHsia3R5Ijoib2N0Iiwia2lkIjoiZlFJZGJmMGZGRiIsImsiOiJFTXdCS2VKTXZZVndGMHhqYjJ4RW5UdHROVFZKcWJSc01ZWXBfMkJGb2lrIn0seyJrdHkiOiJvY3QiLCJraWQiOiJDMzlEODNzUWIzIiwiayI6IndBYnNlVGJtT1pzdFNKVDZuUDNPbnhtNXdxTUdGQ01sSmx2WXhtRlFJREkifSx7Imt0eSI6Im9jdCIsImtpZCI6Ikt1ZTVJNGdnR0IiLCJrIjoiWmpveXcwMWFVdmstV1hSc3VJOUs4dXBjWVRqWEpEMWYyMVJCd1hiTGN0ayJ9LHsia3R5Ijoib2N0Iiwia2lkIjoiVWw1Z2tiQ1hyQyIsImsiOiJjSmlwQy1EWlplQmYzZXdHYmlFeWhSLXRHYmFodk05TEhTVGZnVkJKdm5vIn1dfQ==