# This defines the deployment (as a stateful set) of the pingdirectory servers

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingdirectory
spec:
  serviceName: pingdirectory
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      annotations:
        lastUpdateReason: "NA"
    spec:
      serviceAccount: ping-serviceaccount
      affinity:
        podAntiAffinity:
          # Add a hard requirement for each PD pod to be deployed to a different node
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: role
                operator: In
                values:
                - pingdirectory
            topologyKey: "kubernetes.io/hostname"
          # Add a soft requirement for each PD pod to be deployed to a different AZ
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: role
                  operator: In
                  values:
                  - pingdirectory
              topologyKey: "failure-domain.beta.kubernetes.io/zone"
      terminationGracePeriodSeconds: 300
      initContainers:
      - name: pingdirectory-init
        # FIXME: switch to same user as app
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        image: curlimages/curl
        imagePullPolicy: Always
        command:
        - /init.sh
        envFrom:
        - configMapRef:
            name: pingdirectory-environment-variables
        volumeMounts:
        - name: ssh-dir
          mountPath: /.ssh
        - name: data-dir
          mountPath: /data
        - name: ssh-id-key-secret
          mountPath: /id_rsa
          subPath: id_rsa
        - name: known-hosts-config
          mountPath: /known_hosts
          subPath: known_hosts
        - name: pingdirectory-init
          mountPath: /init.sh
          subPath: init.sh
      containers:
      - name: pingdirectory
        # FIXME: switch to stable image before GA
        image: pingidentity/pingdirectory:8.0.0.0-alpine-edge
        imagePullPolicy: Always
        ports:
        - containerPort: 389
          name: ldap
        - containerPort: 1636
          name: ldaps
        resources:
          requests:
            memory: "5Gi"
            cpu: "2"
          limits:
            memory: "5Gi"
            cpu: "2"
        env:
        - name: MAX_HEAP_SIZE
          value: 4g
        - name: ROOT_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pingdirectory-passwords
              key: root-user-password
        envFrom:
        - configMapRef:
            name: pingdirectory-environment-variables
        - secretRef:
            name: devops-secret
            optional: true
        volumeMounts:
        # FIXME: fix home directory when containers run as non-root user
        - name: ssh-dir
          mountPath: /root/.ssh
        - name: data-dir
          mountPath: /opt/staging/topology.json
          subPath: topology.json
        - name: data-dir
          mountPath: /usr/local/bin/kubectl
          subPath: kubectl
        - name: out-dir
          mountPath: /opt/out
        - name: pingdirectory-passwords
          mountPath: /usr/local/secrets
          readOnly: true
        - name: pingdirectory-license
          mountPath: /opt/in/instance/PingDirectory.lic
          subPath: PingDirectory.lic
        - name: pingdirectory-ready
          mountPath: /opt/staging/readiness.sh
          subPath: readiness.sh
        - name: pingdirectory-pre-stop
          mountPath: /opt/staging/pre-stop.sh
          subPath: pre-stop.sh
        - name: pingdirectory-post-start
          mountPath: /opt/staging/hooks/80-post-start.sh
          subPath: 80-post-start.sh
        readinessProbe:
          exec:
            command:
            - /opt/staging/readiness.sh
          periodSeconds: 30
          failureThreshold: 120
        livenessProbe:
          exec:
            command: [ liveness.sh ]
          initialDelaySeconds: 600
          periodSeconds: 30
          failureThreshold: 10
        lifecycle:
          preStop:
            exec:
              command:
              - /opt/staging/pre-stop.sh
      - name: pingdirectory-statsd-exporter
        image: prom/statsd-exporter
        args:
        - "--statsd.mapping-config=/tmp/mapping/pingdirectory-statsd-mapping.yml"
        - "--statsd.listen-udp=:8125"
        - "--web.listen-address=:9102"
        ports:
          - containerPort: 9102
            protocol: TCP
          - containerPort: 8125
            protocol: UDP
        volumeMounts:
          - mountPath: /tmp/mapping/
            name: pingdirectory-statsd-mapping
            readOnly: false
      volumes:
      - name: ssh-dir
        emptyDir: {}
      - name: data-dir
        emptyDir: {}
      - name: pingdirectory-init
        configMap:
          name: pingdirectory-init
          defaultMode: 0555
      - name: pingdirectory-pre-stop
        configMap:
          name: pingdirectory-pre-stop
          defaultMode: 0555
      - name: pingdirectory-ready
        configMap:
          name: pingdirectory-ready
          defaultMode: 0555
      - name: pingdirectory-post-start
        configMap:
          name: pingdirectory-post-start
          defaultMode: 0555
      - name: ssh-id-key-secret
        secret:
          secretName: ssh-id-key-secret
          optional: true
          defaultMode: 0400
      - name: known-hosts-config
        configMap:
          name: known-hosts-config
          optional: true
          defaultMode: 0644
      - name: out-dir
        persistentVolumeClaim:
          claimName: out-dir
      - name: pingdirectory-license
        secret:
          secretName: pingdirectory-license
          optional: true
          defaultMode: 0400
      - name: pingdirectory-passwords
        secret:
          secretName: pingdirectory-passwords
          optional: true
          defaultMode: 0400
      - name: pingdirectory-statsd-mapping
        configMap:
          name: pingdirectory-statsd-mapping
  volumeClaimTemplates:
  - metadata:
      name: out-dir
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: pingdirectory-gp2
      resources:
        requests:
          storage: 5Gi