# This defines the passwords required for root users of pingdirectory (used by the backup cron job)

apiVersion: v1
kind: Secret
metadata:
  name: pingdirectory-passwords
type: Opaque
data:
  root-user-password: MkZlZGVyYXRlTTByZQ==
  admin-user-password: MkZlZGVyYXRlTTByZQ==
  encryption-password: MkZlZGVyYXRlTTByZQ==

---

apiVersion: v1
kind: Secret
metadata:
  name: pingdirectory-license
type: Opaque