kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../base

patchesStrategicMerge:
- pingdirectory-tunnel.yaml

patchesJson6902:

# Point the pingdirectory load balancer to the stunnel port
- target:
    version: v1
    kind: Service
    name: pingdirectory-admin
  patch: |-
    - op: replace
      path: /spec/ports/0/targetPort
      value:
        stunnel